use bonus_management;


insert INTO `currency` (name, iso_code, iso_number, symbol, currency_type) VALUES
 ('Afghani', 'AFN', 971, '؋', 'FIAT'),
 ('Lek', 'ALL', 008, 'Lek','FIAT'),
 ('Algerian Dinar', 'DZD', 012, 'DA', 'FIAT'),
 ('US Dollar', 'USD', 840, '$', 'FIAT'),
 ('Euro', 'EUR', 978, '€', 'FIAT'),
 ('Kwanza', 'AOA', 973, 'Kz', 'FIAT'),
 ('East Caribbean Dollar','XCD',951, '$', 'FIAT'),
 ('Argentine Peso', 'ARS', 032, '$', 'FIAT'),
 ('Armenian Dram', 'AMD', 051, '֏', 'FIAT'),
 ('Aruban Florin', 'AWG', 533, 'ƒ', 'FIAT'),
 ('Australian Dollar', 'AUD', 036, 'AUS$', 'FIAT'),
 ('Azerbaijanian Manat', 'AZN', 944, 'ман', 'FIAT'),
 ('Bahamian Dollar', 'BSD', 044, 'B$', 'FIAT'),
 ('Bahraini Dinar', 'BHD', 048, 'BD', 'FIAT'),
 ('Taka', 'BDT', 050, '৳', 'FIAT'),
 ('Barbados Dollar','BBD', 052, 'Bds$', 'FIAT'),
 ('Belarussian Ruble', 'BYN', 933, 'Br', 'FIAT'),
 ('Belize Dollar', 'BZD', 084, 'BZ$', 'FIAT'),
 ('CFA Franc BCEAO', 'XOF', 952, 'CFA', 'FIAT'),
 ('Bermudian Dollar', 'BMD', 060, 'BD$', 'FIAT'),
 ('Ngultrum', 'BTN', 064, 'Nu', 'FIAT'),
 ('Indian Rupee', 'INR', 356, '₹', 'FIAT'),
 ('Bolivianos','BOB', 068, '$b', 'FIAT'),
 ('Mvdol','BOV', 984, '$b', 'FIAT'),
 ('Convertible Marka','BAM', 977, 'KM', 'FIAT'),
 ('Pula', 'BWP', 072, 'P', 'FIAT'),
 ('Norwegian Krone', 'NOK', 578, 'kr', 'FIAT'),
 ('Brazilian Real', 'BRL', 986, 'R$', 'FIAT'),
 ('Brunei Dollar', 'BND', 096, 'B$', 'FIAT'),
 ('Bulgarian Lev', 'BGN,', 975, 'Лв', 'FIAT'),
 ('Burundi Franc', 'BIF', 108, 'FBu', 'FIAT'),
 ('Cabo Verde Escudo', 'CVE', 132, 'Esc', 'FIAT'),
 ('Riel', 'KHR', 116, '៛', 'FIAT'),
 ('CFA Franc BEAC', 'XAF', 950, 'FCFA', 'FIAT'),
 ('Canadian Dollar', 'CAD', 124, 'CAD$', 'FIAT'),
 ('Cayman Islands Dollar', 'KYD', 136, 'CI$', 'FIAT'),
 ('Unidad de Fomento', 'CLF', 990, 'UF', 'FIAT'),
 ('Chilean Peso', 'CLP', 152, 'CLP$', 'FIAT'),
 ('Yuan Renminbi', 'CNY', 156, 'CN¥', 'FIAT'),
 ('Colombian Peso', 'COP', 170, 'COL$', 'FIAT'),
 ('Comoro Franc', 'KMF', 174, 'CF', 'FIAT'),
 ('Congolese Franc', 'CDF', 976, 'FC', 'FIAT'),
 ('New Zealand Dollar', 'NZD', 554, 'NZ$', 'FIAT'),
 ('Costa Rican Colon', 'CRC', 188, '₡', 'FIAT'),
 ('Kuna', 'HRK', 191, 'kn', 'FIAT'),
 ('Peso Convertible', 'CUC', 931, 'CUC$', 'FIAT'),
 ('Cuban Peso', 'CUP', 192, '₱', 'FIAT'),
 ('Netherlands Antillean Guilder', 'ANG', 532, 'NAf', 'FIAT'),
 ('Czech Koruna', 'CZK', 203, 'Kč', 'FIAT'),
 ('Danish Krone', 'DKK', 208, 'Kr', 'FIAT'),
 ('Djibouti Franc', 'DJF', 262, 'Fdj', 'FIAT'),
 ('Dominican Peso', 'DOP', 214, 'RD$', 'FIAT'),
 ('Egyptian Pound', 'EGP', 818, 'E£', 'FIAT'),
 ('El Salvador Colon', 'SVC', 222, 'SVC', 'FIAT'),
 ('Nakfa', 'ERN', 232, 'ናቕፋ', 'FIAT'),
 ('Ethiopian Birr', 'ETB', 230, 'ብር', 'FIAT'),
 ('Falkland Islands Pound', 'FKP', 238, '£', 'FIAT'),
 ('Danish Krone', 'DKK', 208, 'Kr', 'FIAT'),
 ('Fiji Dollar', 'FJD', 242, 'FJ$', 'FIAT'),
 ('CFP Franc', 'XPF', 953, '₣', 'FIAT'),
 ('Dalasi', 'GMD', 270, 'D', 'FIAT'),
 ('Lari', 'GEL', 981, 'ლ', 'FIAT'),
 ('Ghana Cedi', 'GHS', 936, 'GH¢', 'FIAT'),
 ('Gibraltar Pound', 'GIP', 292, '£', 'FIAT'),
 ('Danish Krone', 'DKK', 208, 'Kr', 'FIAT'),
 ('Quetzal', 'GTQ', 320, 'Q', 'FIAT'),
 ('Pound Sterling', 'GBP', 826, '£', 'FIAT'),
 ('Guinea Franc', 'GNF', 324, 'FG', 'FIAT'),
 ('Guyana Dollar', 'GYD', 328, 'GY$', 'FIAT'),
 ('Gourde', 'HTG', 332, 'G', 'FIAT'),
 ('Lempira', 'HNL', 340, 'L', 'FIAT'),
 ('Hong Kong Dollar', 'HKD', 344, 'hk$', 'FIAT'),
 ('Forint', 'HUF', 348, 'Ft', 'FIAT'),
 ('Iceland Krona', 'ISK', 352, 'kr', 'FIAT'),
 ('Indian Rupee', 'INR', 356, '₹', 'FIAT'),
 ('Rupiah', 'IDR', 360, 'Rp', 'FIAT'),
 ('Iranian Rial', 'IRR', '364', '﷼', 'FIAT'),
 ('Iraqi Dinar', 'IQD', 368, 'ع.د', 'FIAT'),
 ('New Israeli Sheqel', 'ILS', 376, '₪', 'FIAT'),
 ('Jamaican Dollar', 'JMD', 388, 'J$', 'FIAT'),
 ('Yen', 'JPY', 392, '¥', 'FIAT'),
 ('Jordanian Dinar', 'JOD', 400, 'د.ا', 'FIAT'),
 ('Tenge', 'KZT', 398, '₸', 'FIAT'),
 ('Kenyan Shilling', 'KES', 404, 'Ksh', 'FIAT'),
 ('North Korean Won', 'KPW', 408, '₩', 'FIAT'),
 ('Won', 'KRW', 410, '₩', 'FIAT'),
 ('Kuwaiti Dinar', 'KWD', 414, 'KD', 'FIAT'),
 ('Som', 'KGS', 417, 'Лв', 'FIAT'),
 ('Kip', 'LAK', 418, '₭', 'FIAT'),
 ('Lebanese Pound', 'LBP', 422, '£L', 'FIAT'),
 ('Loti', 'LSL', 426, 'L', 'FIAT'),
 ('Rand', 'ZAR', 710, 'R', 'FIAT'),
 ('Liberian Dollar', 'LRD', 430, 'L$', 'FIAT'),
 ('Libyan Dinar', 'LYD', 434, 'LD', 'FIAT'),
 ('Swiss Franc', 'CHF', 756, 'CHf', 'FIAT'),
 ('Pataca', 'MOP', 446, 'MOP$', 'FIAT'),
 ('Malagasy Ariary', 'MGA', 969, 'Ar', 'FIAT'),
 ('Kwacha', 'MWK', 454, 'MK', 'FIAT'),
 ('Malaysian Ringgit', 'MYR', 458, 'RM', 'FIAT'),
 ('Rufiyaa', 'MVR', 462, 'MRf', 'FIAT'),
 ('Ouguiya', 'MRU', 929, 'UM', 'FIAT'),
 ('Mauritius Rupee', 'MUR', 480, 'Rs', 'FIAT'),
 ('Mexican Peso', 'MXN', 484, 'Mex$', 'FIAT'),
 ('Moldovan Leu', 'MDL', 498, 'L', 'FIAT'),
 ('Tugrik', 'MNT', 496, '₮', 'FIAT'),
 ('Moroccan Dirham', 'MAD', 504, 'MAD', 'FIAT'),
 ('Mozambique Metical', 'MZN', 943, 'MT', 'FIAT'),
 ('Kyat', 'MMK', 104, 'K', 'FIAT'),
 ('Namibia Dollar', 'NAD',516, 'N$', 'FIAT'),
 ('Nepalese Rupee', 'NPR', 524, 'रू', 'FIAT'),
 ('CFP Franc', 'XPF', 953, '₣', 'FIAT'),
 ('Cordoba Oro', 'NIO', 558, 'C$', 'FIAT'),
 ('Naira', 'NGN', 566, '₦', 'FIAT'),
 ('Rial Omani', 'OMR', 512, ' ر.ع.', 'FIAT'),
 ('Pakistan Rupee', 'PKR', 586, 'Rs', 'FIAT'),
 ('Balboa', 'PAB', 590, 'B/.', 'FIAT'),
 ('Kina', 'PGK', 598, 'K', 'FIAT'),
 ('Guarani', 'PYG', 600, '₲', 'FIAT'),
 ('Nuevo Sol', 'PEN', 604, 'S/', 'FIAT'),
 ('Philippine Peso', 'PHP', 608, '₱', 'FIAT'),
 ('Zloty', 'PLN', 985, 'zł', 'FIAT'),
 ('Qatari Rial', 'QAR', 634, 'QR', 'FIAT'),
 ('Denar', 'MKD', 807, 'Ден', 'FIAT'),
 ('Romanian Leu', 'RON', 946, 'lei', 'FIAT'),
 ('Russian Ruble', 'RUB', 643, '₽', 'FIAT'),
 ('Rwanda Franc', 'RWF', 646, 'FRw', 'FIAT'),
 ('Saint Helena Pound', 'SHP', 654, '£', 'FIAT'),
 ('Tala', 'WST', 882, 'WS$', 'FIAT'),
 ('Dobra', 'STN',930, 'Db', 'FIAT'),
 ('Saudi Riyal', 'SAR', 682, 'SR', 'FIAT'),
 ('Serbian Dinar', 'RSD', 941, 'din', 'FIAT'),
 ('Seychelles Rupee', 'SCR', 690, 'SR', 'FIAT'),
 ('Leone', 'SLL', 694, 'Le', 'FIAT'),
 ('Singapore Dollar', 'SGD', 702, 'S$', 'FIAT'),
 ('Solomon Islands Dollar', 'SBD', 090, 'Si$', 'FIAT'),
 ('Somali Shilling', 'SOS', 706, 'Sh.so.', 'FIAT'),
 ('South Sudanese Pound', 'SSP', 728, 'SS£', 'FIAT'),
 ('Sri Lanka Rupee', 'LKR', 144, 'Rs', 'FIAT'),
 ('Surinam Dollar', 'SRD', 968, '$', 'FIAT'),
 ('Lilangeni', 'SZL', 748, 'E', 'FIAT'),
 ('Swedish Krona', 'SEK', 752, 'kr', 'FIAT'),
 ('WIR Franc', 'CHW', 948, 'CHW', 'FIAT'),
 ('Syrian Pound', 'SYP', 760, '£S', 'FIAT'),
 ('New Taiwan Dollar', 'TWD', 901, 'NT$', 'FIAT'),
 ('Somoni', 'TJS', 972, 'SM', 'FIAT'),
 ('Tanzanian Shilling', 'TZS',834, 'TSh', 'FIAT'),
 ('Baht', 'THB', 764, '฿', 'FIAT'),
 ('Pa’anga', 'TOP', 776, 'T$', 'FIAT'),
 ('Trinidad and Tobago Dollar', 'TTD', 780, 'TT$', 'FIAT'),
 ('Tunisian Dinar', 'TND', 788, 'DT', 'FIAT'),
 ('Turkish Lira', 'TRY', 949, '₺', 'FIAT'),
 ('Turkmenistan New Manat', 'TMT', 934, 'm', 'FIAT'),
 ('Uganda Shilling', 'UGX', 800, 'USh', 'FIAT'),
 ('Hryvnia', 'UAH', 980, '₴', 'FIAT'),
 ('UAE Dirham', 'AED', 784, 'د.إ', 'FIAT'),
 ('Peso Uruguayo', 'UYU', 858, '$U', 'FIAT'),
 ('Uzbekistan Sum', 'UZS', 860, 'so`m', 'FIAT'),
 ('Vatu', 'VUV', 548, 'VT', 'FIAT'),
 ('Bolivar', 'VEF', 937, 'Bs.', 'FIAT'),
 ('Dong', 'VND', 704, '₫', 'FIAT'),
 ('Yemeni Rial', 'YER', 886, '﷼', 'FIAT'),
 ('Zambian Kwacha', 'ZMW', 967,'ZK', 'FIAT'),
 ('Zimbabwe Dollar', 'ZWL', 932, 'Z$' ,'FIAT');